apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    app: nginx-staging
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
